### ISSUE TITLE
pip install fiber error with Python 3.8 on macOS

### ISSUE THREAD

**Issue by statmike** [uber/fiber#26]
I get this error with pip install fiber:

`ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

To get this far I first did these:
`pip install wheel`
`brew install nanomsg`
installed nanomsg 1.1.5
`pip install nnpy`

I appreciate any help getting past this.  I can provide more of the error log if needed.

**Comment by calio** [comment]
Hi @statmike, could you provide the full log of the installation? Also, `fiber` moved away from `nnpy` and switched to `nnpy-bundle` which is a all-inclusive package that doesn't need to `brew install nanomsg` manually.

**Comment by statmike** [comment]
a full log follows and does show the issue is with the install of `nnpy-bundle`.  I tried `pip install nnpy-bundle` and got the same error.

Collecting fiber
  Using cached fiber-0.2.1.tar.gz (61 kB)
Collecting nnpy-bundle
  Using cached nnpy-bundle-1.4.2.post1.tar.gz (6.3 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/statmike/.pyenv/versions/3.8.0/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/1q/vpw647m96rv48y4sbc9_4xrw0000gn/T/pip-install-d3nkeklm/nnpy-bundle/setup.py'"'"'; __file__='"'"'/private/var/folders/1q/vpw647m96rv48y4sbc9_4xrw0000gn/T/pip-install-d3nkeklm/nnpy-bundle/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/1q/vpw647m96rv48y4sbc9_4xrw0000gn/T/pip-pip-egg-info-yl7j3acw
         cwd: /private/var/folders/1q/vpw647m96rv48y4sbc9_4xrw0000gn/T/pip-install-d3nkeklm/nnpy-bundle/
    Complete output (51 lines):
    Cloning into 'nanomsg'...
    Note: switching to '1.1.5'.
    
    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by switching back to a branch.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -c with the switch command. Example:
    
      git switch -c <new-branch-name>
    
    Or undo this operation with:
    
      git switch -
    
    Turn off this advice by setting config variable advice.detachedHead to false
    
    HEAD is now at 1749fd7b Bump version to 1.1.5.
    /bin/sh: cmake: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1q/vpw647m96rv48y4sbc9_4xrw0000gn/T/pip-install-d3nkeklm/nnpy-bundle/setup.py", line 22, in <module>
        setup(
      File "/Users/statmike/.pyenv/versions/3.8.0/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/Users/statmike/.pyenv/versions/3.8.0/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/statmike/.pyenv/versions/3.8.0/lib/python3.8/site-packages/setuptools/dist.py", line 429, in __init__
        _Distribution.__init__(self, {
      File "/Users/statmike/.pyenv/versions/3.8.0/lib/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/Users/statmike/.pyenv/versions/3.8.0/lib/python3.8/site-packages/setuptools/dist.py", line 721, in finalize_options
        ep(self)
      File "/Users/statmike/.pyenv/versions/3.8.0/lib/python3.8/site-packages/setuptools/dist.py", line 728, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/Users/statmike/.pyenv/versions/3.8.0/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/Users/statmike/.pyenv/versions/3.8.0/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/Users/statmike/.pyenv/versions/3.8.0/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "generate.py", line 199, in <module>
        ffi = create_module()
      File "generate.py", line 142, in create_module
        build_nanomsg_static_lib(cwd)
      File "generate.py", line 66, in build_nanomsg_static_lib
        check_call('cmake "-DCMAKE_C_FLAGS=-fPIC" "-DCMAKE_INSTALL_PREFIX=dest" "-DNN_STATIC_LIB=ON" ..', shell=True, cwd=build_dir)
      File "/Users/statmike/.pyenv/versions/3.8.0/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'cmake "-DCMAKE_C_FLAGS=-fPIC" "-DCMAKE_INSTALL_PREFIX=dest" "-DNN_STATIC_LIB=ON" ..' returned non-zero exit status 127.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by calio** [comment]
Seems that `cmake` is missing. Can you try `brew install cmake`?

**Comment by statmike** [comment]
Hi @calio,
That was it!  After `brew install cmake`, `pip install fiber` was successful.  This issue can be closed.
Thank You!
