### ISSUE TITLE
Installation issue with pip install fiber on Windows 10, Python 3.8, via conda

### ISSUE THREAD

**Issue by maxenceryan** [uber/fiber#37]
Hi all,

I am getting an error when running  `pip install fiber` in my conda (v4.8.3) environment. It seems to do with a `make -j8` command failing and saying at the top that no makefile was found. Was it perhaps not generated via `nnpy-bundle`? Or should I install first a previous version of nanomsg?

Any help would be greatly appreciated!

Make installed and in path:
```
$ make -version
GNU Make 4.3
Built for Windows32
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Input in command prompt:
```
$ pip install fiber
```

Output: (I've replaced my user directory with ~)
```
Collecting fiber
  Using cached fiber-0.2.1.tar.gz (61 kB)
Collecting nnpy-bundle
  Using cached nnpy-bundle-1.4.2.post1.tar.gz (6.3 kB)
    ERROR: Command errored out with exit status 1:
     command: '~\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'~\\AppData\\Local\\Temp\\pip-install-4ws65jt4\\nnpy-bundle\\setup.py'"'"'; __file__='"'"'~\\AppData\\Local\\Temp\\pip-install-4ws65jt4\\nnpy-bundle\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base '~\AppData\Local\Temp\pip-install-4ws65jt4\nnpy-bundle\pip-egg-info'
         cwd: ~\AppData\Local\Temp\pip-install-4ws65jt4\nnpy-bundle\
    Complete output (77 lines):
    Cloning into 'nanomsg'...
    Note: switching to '1.1.5'.

    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by switching back to a branch.

    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -c with the switch command. Example:

      git switch -c <new-branch-name>

    Or undo this operation with:

      git switch -

    Turn off this advice by setting config variable advice.detachedHead to false

    HEAD is now at 1749fd7b Bump version to 1.1.5.
    -- Building for: Visual Studio 16 2019
    -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
    -- The C compiler identification is MSVC 19.24.28314.0
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe - works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detected nanomsg ABI v5 (v5.1.0)
    -- Looking for pthread.h
    -- Looking for pthread.h - not found
    -- Found Threads: TRUE
    -- OS System is Windows
    -- OS Version is 10.0.19041
    -- Looking for InitializeConditionVariable
    -- Looking for InitializeConditionVariable - found
    -- Performing Test NN_HAVE_GCC_ATOMIC_BUILTINS
    -- Performing Test NN_HAVE_GCC_ATOMIC_BUILTINS - Failed
    CMake Warning at CMakeLists.txt:294 (message):
      Could not find asciidoctor: skipping docs


    -- Configuring done
    -- Generating done
    -- Build files have been written to: ~/AppData/Local/Temp/pip-install-4ws65jt4/nnpy-bundle/nanomsg/build
    make: *** No targets specified and no makefile found.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "~\AppData\Local\Temp\pip-install-4ws65jt4\nnpy-bundle\setup.py", line 47, in <module>
        install_requires=['cffi'],
      File "~\Anaconda3\lib\site-packages\setuptools\__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "~\Anaconda3\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "~\Anaconda3\lib\site-packages\setuptools\dist.py", line 425, in __init__
        k: v for k, v in attrs.items()
      File "~\Anaconda3\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "~\Anaconda3\lib\site-packages\setuptools\dist.py", line 706, in finalize_options
        ep.load()(self)
      File "~\Anaconda3\lib\site-packages\setuptools\dist.py", line 713, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "~\Anaconda3\lib\site-packages\cffi\setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "~\Anaconda3\lib\site-packages\cffi\setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "~\Anaconda3\lib\site-packages\cffi\setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "generate.py", line 199, in <module>
        ffi = create_module()
      File "generate.py", line 142, in create_module
        build_nanomsg_static_lib(cwd)
      File "generate.py", line 67, in build_nanomsg_static_lib
        check_call("make -j8", shell=True, cwd=build_dir)
      File "~\Anaconda3\lib\subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'make -j8' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by calio** [comment]
Hi @maxenceryan , thanks for trying out Fiber. As we stated in https://uber.github.io/fiber/platforms/, Windows is not currently supported. I would like to add that support later, in the meantime, you can try Fiber on Linux / OSX.

**Comment by maxenceryan** [comment]
Hi @calio, thank you for reply and apologies for not reading the documentation through, it did work in a linux docker just fine so I will try in WSL for now.
